const keyDisplayNames: Record<string, string> = {
    species: "Species",
    tag: "Tag Number",
    breed: "Breed",
    gender: "Gender",
    weight: "Weight",
    age: "Age",
    status:"Status",
    dam: "Dam",
    sire: "Sire",
    birthWeight: "Birth Weight",
    lastCalvingDate:"Last Calving Date",
    lactationStage:"Lactation Stage",
    lastAiDate: "Last Ai Date",
    nextAiDate:"Next Ai Date",
    pregnancyStatus: "Pregnancy Status",
    ageOfPregnancy: "Age of Pregnancy Status",
    expectedCalvingDate: "Expected Calving Date",
    lastHeatDate: "Last Heat Date",
    reproductiveComment: "Reproductive Comment",
    vaccinationType: "Vaccination Type",
    vaccinationDate: "Vaccination Date",
    nextVaccinationDate: "Next Vaccination Date",
    dewormingType: "Deworming Type",
    lastDewormingDate: "Last Deworming Date",
    nextDewormingDate: "Next Deworming Date",
    diseaseComment: "Diseases Comment",
    treatmentComment: "Treatment Comment",
};

export default keyDisplayNames;
