// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
//import { AuthProvider } from "@/context/AuthContext";
import { AnimalProvider } from "@/context/AnimalContext";
import { TasksProvider } from "@/context/TasksContext";
import { UserProvider } from "@/context/UserContext";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Teaching Farm Peradeniya",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
        <body className="antialiased">
       <UserProvider>

               <AnimalProvider> {/* ✅ Wrap children with AnimalProvider */}
                   <TasksProvider>
                       {children}
                   </TasksProvider>
               </AnimalProvider>
       </UserProvider>


        </body>
        </html>
    );
}
